"use client";
import "./Historial.css"
import AntecedentesFamiliares from "./historial/AntecedentesFamiliares";
import AntecedentesObstetricos from "./historial/AntecedentesObstetricos";
import AntecedentesQuirurgicos from "./historial/AntecedentesQuirurgicos";
import DatosMentruales from "./historial/DatosMenstruales";
import EmbarazoActual from "./historial/EmbarazoActual";
import ExamenFisico from "./historial/ExamenFisico";
import Gesta from "./historial/Gesta";
import HistoriaMedicaPasada from "./historial/HistoriaMedicaPasada";
import HistoriaObstetrica from "./historial/HistoriaObstetrica";

import { useState } from 'react';

export default function Historial({
    edit,
    embarazos,
    numero_de_historia,
    fecha,
    revisada,
    clasificada,
    archivada,
    centro_asistencial,
    tipo,
    codigo_de_origen,
    ubicacion_geografica,
    nombre,
    cedula_de_identidad,
    edad,
    fecha_de_nacimiento,
    lugar_de_nacimiento,
    estado_civil,
    profesion,
    ocupacion,
    direccion_de_habitacion,
    telefono,
    nombre_conyugue,
    direccion_conyugue,
    antecedentes_familiares_tbc,
    antecedentes_familiares_sifilis,
    antecedentes_familiares_diabetes,
    antecedentes_familiares_neurologicas_y_mentales,
    antecedentes_familiares_cardiopatias,
    antecedentes_familiares_nefritis,
    antecedentes_familiares_embarazos_multiples,
    antecedentes_familiares_otros,
    antecedentes_familiares_cancer,
    datos_menstruales_edad_menarquia,
    datos_menstruales_ciclo,
    datos_menstruales_duracion,
    datos_menstruales_cantidad,
    datos_menstruales_dolor,
    historia_medica_pasada_eruptivas,
    historia_medica_pasada_buba,
    historia_medica_pasada_cardiopatias,
    historia_medica_pasada_toxemias,
    historia_medica_pasada_mastitis,
    historia_medica_pasada_transfusiones,
    historia_medica_pasada_rubeola,
    historia_medica_pasada_chagas,
    historia_medica_pasada_tbc,
    historia_medica_pasada_varices,
    historia_medica_pasada_heridas,
    historia_medica_pasada_alergias,
    historia_medica_pasada_parasitosis,
    historia_medica_pasada_toxoplasmosis,
    historia_medica_pasada_diabetes,
    historia_medica_pasada_hemorroides,
    historia_medica_pasada_cicatrices,
    historia_medica_pasada_sulfonamidas,
    historia_medica_pasada_bilharziosis,
    historia_medica_pasada_micosis,
    historia_medica_pasada_tiroides,
    historia_medica_pasada_flebitis,
    historia_medica_pasada_fracturas,
    historia_medica_pasada_antibioticos,
    historia_medica_pasada_paludismo,
    historia_medica_pasada_nefropatias,
    historia_medica_pasada_electrocoagulaciones,
    historia_medica_pasada_otro,
    antecedentes_quirurgicos,
    embarazo_actual_ultimo_periodo,
    embarazo_actual_caracteres,
    embarazo_actual_primeros_movimientos,
    embarazo_actual_fecha_parto_probable,
    embarazo_actual_reposo_prenatal_desde,
    nombre_medico,
    registro_mpps,
    firma,
    examen_fisico_talla,
    examen_fisico_peso_previo,
    examen_fisico_aspecto_general,
    examen_fisico_edemas,
    examen_fisico_piel,
    examen_fisico_senos,
    examen_fisico_sistema_nervioso,
    examen_fisico_abdomen,
    examen_fisico_aparato_digestivo,
    examen_fisico_vulva_y_perine,
    examen_fisico_aparato_circulatorio,
    examen_fisico_vagina,
    examen_fisico_aparato_respiratorio,
    examen_fisico_cuello,
    examen_fisico_rx_pulmonar,
    examen_fisico_cuerpo_uterino,
    examen_fisico_aparato_urinario,
    examen_fisico_aparato_locomotor,
    examen_fisico_sistema_ganglionar,
    examen_fisico_varices,
    examen_fisico_otros,
    createdAt,
    updatedAt,
}){
    return (
        <div className="flex_col gap_lg padding_lg">
            <HistoriaObstetrica
            edit={edit}
            numero_de_historia={numero_de_historia}
            fecha={fecha} 
            revisada={revisada}
            clasificada={clasificada} 
            archivada={archivada}
            centro_asistencial={centro_asistencial}
            tipo={tipo}
            codigo_de_origen={codigo_de_origen}
            ubicacion_geografica={ubicacion_geografica}
            nombre={nombre}
            cedula_de_identidad={cedula_de_identidad}
            edad={edad}
            fecha_de_nacimiento={fecha_de_nacimiento}
            lugar_de_nacimiento={lugar_de_nacimiento}
            //estado_civil={estado_civil}
            profesion={profesion}
            ocupacion={ocupacion}
            direccion_de_habitacion={direccion_de_habitacion}
            telefono={telefono}
            nombre_conyugue={nombre_conyugue}
            direccion_conyugue={direccion_conyugue}
            />
            <AntecedentesFamiliares
              antecedentes_familiares_tbc={antecedentes_familiares_tbc}
              antecedentes_familiares_sifilis={antecedentes_familiares_sifilis}
              antecedentes_familiares_diabetes={antecedentes_familiares_diabetes}
              antecedentes_familiares_neurologicas_y_mentales={antecedentes_familiares_neurologicas_y_mentales}
              antecedentes_familiares_cardiopatias={antecedentes_familiares_cardiopatias}
              antecedentes_familiares_nefritis={antecedentes_familiares_nefritis}
              antecedentes_familiares_embarazos_multiples={antecedentes_familiares_embarazos_multiples}
              antecedentes_familiares_otros={antecedentes_familiares_otros}
              antecedentes_familiares_cancer={antecedentes_familiares_cancer}
            />
            <DatosMentruales
            datos_menstruales_edad_menarquia={datos_menstruales_edad_menarquia}
            datos_menstruales_ciclo={datos_menstruales_ciclo}
            datos_menstruales_duracion={datos_menstruales_duracion}
            datos_menstruales_cantidad={datos_menstruales_cantidad}
            datos_menstruales_dolor={datos_menstruales_dolor}
            />
            <HistoriaMedicaPasada
            historia_medica_pasada_eruptivas={historia_medica_pasada_eruptivas}
            historia_medica_pasada_buba={historia_medica_pasada_buba}
            historia_medica_pasada_cardiopatias={historia_medica_pasada_cardiopatias}
            historia_medica_pasada_toxemias={historia_medica_pasada_toxemias}
            historia_medica_pasada_mastitis={historia_medica_pasada_mastitis}
            historia_medica_pasada_transfusiones={historia_medica_pasada_transfusiones}
            historia_medica_pasada_rubeola={historia_medica_pasada_rubeola}
            historia_medica_pasada_chagas={historia_medica_pasada_chagas}
            historia_medica_pasada_tbc={historia_medica_pasada_tbc}
            historia_medica_pasada_varices={historia_medica_pasada_varices}
            historia_medica_pasada_heridas={historia_medica_pasada_heridas}
            historia_medica_pasada_alergias={historia_medica_pasada_alergias}
            historia_medica_pasada_parasitosis={historia_medica_pasada_parasitosis}
            historia_medica_pasada_toxoplasmosis={historia_medica_pasada_toxoplasmosis}
            historia_medica_pasada_diabetes={historia_medica_pasada_diabetes}
            historia_medica_pasada_hemorroides={historia_medica_pasada_hemorroides}
            historia_medica_pasada_cicatrices={historia_medica_pasada_cicatrices}
            historia_medica_pasada_sulfonamidas={historia_medica_pasada_sulfonamidas}
            historia_medica_pasada_bilharziosis={historia_medica_pasada_bilharziosis}
            historia_medica_pasada_micosis={historia_medica_pasada_micosis}
            historia_medica_pasada_tiroides={historia_medica_pasada_tiroides}
            historia_medica_pasada_flebitis={historia_medica_pasada_flebitis}
            historia_medica_pasada_fracturas={historia_medica_pasada_fracturas}
            historia_medica_pasada_antibioticos={historia_medica_pasada_antibioticos}
            historia_medica_pasada_paludismo={historia_medica_pasada_paludismo}
            historia_medica_pasada_nefropatias={historia_medica_pasada_nefropatias}
            historia_medica_pasada_electrocoagulaciones={historia_medica_pasada_electrocoagulaciones}
            historia_medica_pasada_otro={historia_medica_pasada_otro}
            />
            <AntecedentesQuirurgicos antecedentes_quirurgicos={antecedentes_quirurgicos}/>
            <EmbarazoActual
            embarazo_actual_ultimo_periodo={embarazo_actual_ultimo_periodo}
            embarazo_actual_caracteres={embarazo_actual_caracteres}
            embarazo_actual_primeros_movimientos={embarazo_actual_primeros_movimientos}
            embarazo_actual_fecha_parto_probable={embarazo_actual_fecha_parto_probable}
            embarazo_actual_reposo_prenatal_desde={embarazo_actual_reposo_prenatal_desde}
            />
            <Gesta
                nombre_medico={nombre_medico}
                registro_mpps={registro_mpps}
            />
            <AntecedentesObstetricos embarazos={embarazos}/>
            <ExamenFisico
            examen_fisico_talla={examen_fisico_talla}
            examen_fisico_peso_previo={examen_fisico_peso_previo}
            examen_fisico_aspecto_general={examen_fisico_aspecto_general}
            examen_fisico_edemas={examen_fisico_edemas}
            examen_fisico_piel={examen_fisico_piel}
            examen_fisico_senos={examen_fisico_senos}
            examen_fisico_sistema_nervioso={examen_fisico_sistema_nervioso}
            examen_fisico_abdomen={examen_fisico_abdomen}
            examen_fisico_aparato_digestivo={examen_fisico_aparato_digestivo}
            examen_fisico_vulva_y_perine={examen_fisico_vulva_y_perine}
            examen_fisico_aparato_circulatorio={examen_fisico_aparato_circulatorio}
            examen_fisico_vagina={examen_fisico_vagina}
            examen_fisico_aparato_respiratorio={examen_fisico_aparato_respiratorio}
            examen_fisico_cuello={examen_fisico_cuello}
            examen_fisico_rx_pulmonar={examen_fisico_rx_pulmonar}
            examen_fisico_cuerpo_uterino={examen_fisico_cuerpo_uterino}
            examen_fisico_aparato_urinario={examen_fisico_aparato_urinario}
            examen_fisico_aparato_locomotor={examen_fisico_aparato_locomotor}
            examen_fisico_sistema_ganglionar={examen_fisico_sistema_ganglionar}
            examen_fisico_varices={examen_fisico_varices}
            examen_fisico_otros={examen_fisico_otros}
            />
        </div>
    )
}